config/routes.rb
# firehose track 5, lesson 5 - file created 10 jul 17 for writing first test

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "grams#index"
  
  # next 3 lines added 12 jul 17 for comments (lesson 18)
  resources :grams do
    resources :comments, only: :create
  end

# next line added 11 jul 17 for adding grams in db, gram detail page, edit/update grams, destroy grams (lessons 7, 12-14),
# then deleted in favor of the "resources" way of using the same actions
#  resources :grams, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :grams
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# firehose track 5, lesson 18 - file created 12 jul 17 for comments

class Comment < ApplicationRecord
  belongs_to :gram
  belongs_to :user
end

app/models/gram.rb
class Gram < ApplicationRecord
  
# next line added 11 jul 17 for gram validations (lesson 9)
  validates :message, presence: true      # validates messages aren't blank
# next line added 12 jul 17 for image validations (lesson 17)
  validates :picture, presence: true
# next line added 12 jul 17 for comments (lesson 18)
  has_many :comments
  
# next line added 11 jul 17 for connecting a gram with a user (lesson 10)
  belongs_to :user
  
# next line added 12 jul 17 for uploading images (lesson/challenge 16)
  mount_uploader :picture, PictureUploader
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
# next line added 11 jul 17 for connecting a gram with a user (lesson 10)
         has_many :grams
# next line added 12 jul 17 for comments (lesson 18)
         has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
# next 3 lines added 12 jul 17 for comments (lesson 18)
  def render_not_found(status=:not_found)
    render plain: "#{status.to_s.titleize} :(", status: status
  end
  
end

app/controllers/comments_controller.rb
# firehose track 5, lesson 18 - file created 12 jul 17 for comments

class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  
  def create
    @gram = Gram.find_by_id(params[:gram_id])
    return render_not_found if @gram.blank?
    
    @gram.comments.create(comment_params.merge(user: current_user))
    redirect_to root_path
  end

  private
  
#  def render_not_found(status=:not_found)
#    render plain: "#{status.to_s.titleize} :(", status: status
#  end

  def comment_params
    params.require(:comment).permit(:message)
  end
end

app/controllers/grams_controller.rb
# firehose track 5, lesson 5 - file created 10 jul 17 for writing first test

class GramsController < ApplicationController
# next line added 11 jul 17/modified 12 jul 17 for connecting a gram with a user, securing edit/update/destroy (lessons 10, 15)
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  
# destroy method added 11 jul 17 for destroying grams (lesson 14)
  def destroy
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
# next 3 lines added/modified 12 jul 17 for securing edit/update/destroy (lesson 15)
#    if @gram.user != current_user
#      return render plain: 'Forbidden :(', status: :forbidden
    return render_not_found(:forbidden) if @gram.user != current_user
#    end
  
    @gram.destroy
    redirect_to root_path
  end
  
# update method added 11 jul 17 for edit/update grams (lesson 13)
  def update
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
# next 3 lines added/modified 12 jul 17 for securing edit/update/destroy (lesson 15)
#    if @gram.user != current_user
#      return render plain: 'Forbidden :(', status: :forbidden
    return render_not_found(:forbidden) if @gram.user != current_user
#    end
    
    @gram.update_attributes(gram_params)
    
    if @gram.valid?
      redirect_to root_path
    else
      return render :edit, status: :unprocessable_entity
    end
  end
  
# new method added 11 jul 17 for adding grams to db (lesson 7)
  def new
    @gram = Gram.new
  end
  
# index method added 11 jul 17 for adding grams to db (lesson 7)
  def index
    @grams = Gram.all     # added 12 jul 17 for uploading images (lesson/challenge 16)
  end
  
# show method added 11 jul 17 for gram detail page, edit/update grams (lessons 12, 13)
  def show
#    @gram = Gram.find(params[:id])
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
  end
  
# edit method added 11 jul 17 for edit/update grams (lesson 13)
  def edit
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
# next 3 lines added/modified 12 jul 17 for securing edit/update/destroy (lesson 15)
#    if @gram.user != current_user
#      render plain: 'Forbidden :(', status: :forbidden
    return render_not_found(:forbidden) if @gram.user != current_user
#    end
    
  end
  
# create method added 11 jul 17 for adding grams to db, validating grams (lessons 7, 9)
  def create
    
    # next line added 11 jul 17 for connecting a gram to a user (lesson 10)
    @gram = current_user.grams.create(gram_params)
#    @gram = Gram.create(gram_params)    # save gram to db

    if @gram.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end
  
# private gram_params method added 11 jul 17 for adding grams to db (lesson 7)
  private

  def gram_params
    params.require(:gram).permit(:message, :picture)  # :picture added 12 jul 17 for uploading images (lesson/challenge 16)
  end
  
# render_not_found method added 11 jul 17 for edit/update grams (lesson 13)

#  def render_not_found
#    render plain: 'Not Found :(', status: :not_found
#  end

# next 3 lines modified 12 jul 17 for securing edit/update/destroy (lesson 15)
#  def render_not_found(status=:not_found)
#    render plain: "#{status.to_s.titleize} :(", status: status
#  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/grams_helper.rb
module GramsHelper
end

app/views/grams/edit.html.erb
<!-- firehose track 5, lesson 13 - file created 11 jul 17 for edit/update grams -->

<!-- next 2 lines added 12 jul 17 for styling (lesson 19) -->
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 card form">
  <h2>Edit Gram</h2>
  
  <%= simple_form_for @gram do |f| %>
    <%= f.input :message %>
    
<!-- next line added 12 jul 17 for styling (lesson 19) -->
    <%= f.input :picture %>
    
    <%= f.submit 'Update', class: 'my-btn' %>   <!-- changed 12 jul 17 for styling (lesson 19) -->
  <% end %>
</div>

app/views/grams/index.html.erb
<!-- firehose track 5, lesson 5 - file created for writing first test -->

<h1>Grams!</h1>

<!-- code block added 12 jul 17 for uploading images (lesson/challenge 16), deleted/modified (new block below) for styling (lesson 19)
<% @grams.each do |gram| %>
<div>
  <%= gram.message %>
  <%= image_tag gram.picture %>
</div>
<% end %>  -->

<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3">
  <% @grams.each do |gram| %>
  <div class="card">
    <div class="handle"><%= gram.user.try(:email) %></div>
    <%= image_tag gram.picture, class: 'img-fluid' %>
    <p>
      <%= gram.message %>
    </p>
    
<!-- code block added 12 jul 17 for styling (lesson 19) -->
    <div class="gram-actions float-right">
      <% if current_user && current_user == gram.user %>
        <%= link_to 'Edit', edit_gram_path(gram) %>
        <%= link_to 'Destroy', gram_path(gram), method: :delete, data: {confirm: 'Are you sure?'} %>
      <% end %>
    </div>
    <br class="clear-fix" />
    
    <div class="comments">
      <h3>Comments</h3>
      <% gram.comments.each do |comment| %>
        <div class="comment">
          <span class="comment_handle">
            <%= comment.user.email %>
          </span>

          <%= comment.message %>
        </div>
      <% end %>

      <h4>Add a comment</h4>
      <%= simple_form_for Comment.new, url: gram_comments_path(gram) do |f| %>
        <%= f.input :message %>
        <%= f.submit 'Add Comment', class: 'my-btn' %>
      <% end %>
    </div>
    
  </div>
  <% end %>
</div>

app/views/grams/new.html.erb
<!-- firehose track 5, lesson 7 - file created 11 jul 17 for adding grams to db -->

<!-- next line added 12 jul 17 for styling (lesson 19) -->
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 card form">
  
  <h1>New Gram</h1>
  
  <%= simple_form_for @gram do |f| %>
    <%= f.input :message %>
<!--    <%= f.submit "Post!" %> -->
    
<!-- next line added 12 jul 17 for uploading images (lesson/challenge 16) -->
    <%= f.input :picture %>
<!-- next line added 12 jul 17 for styling (lesson 19) -->
    <%= f.submit "Post!", class: 'my-btn' %>
  <% end %>
  
</div>

app/views/grams/show.html.erb
<!-- firehose track 5, lesson 12 - file created 11 jul 17 for gram detail page -->

<%= @gram.inspect %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grammable</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<!-- next 2 lines added 12 jul 17 for styling (lesson 19) -->
    <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Josefin+Sans:400,100,300,600,700' rel='stylesheet' type='text/css'>
  </head>

  <body>
    
<!-- next 13 lines added 11 jul 17 for devise authentication (lesson/challenge 8), deleted/modified 12 jul 17 for styling (lesson 19)
    <% if current_user %>
      You're signed in as <%= current_user.email %>.
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign In", new_user_session_path %>
      <%= link_to "Sign Up", new_user_registration_path %>
    <% end %>
    
    <% if notice.present? %>
      <p class="notice"><%= notice %></p>
    <% end %>

    <% if alert.present? %>
      <p class="alert"><%= alert %></p>
    <% end %>  -->
    
<!-- nav bar added 12 jul 17 for styling -->
    <div class="top-nav">
      <div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3">
        <div class="brand float-left">
          Grammable
        </div>
        <div class="add float-right">
          <% if current_user %>
            Welcome, <%= current_user.email %>.
            <%= link_to "New Post", new_gram_path %>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path %>
            <%= link_to "Sign Up", new_user_registration_path %>
          <% end %>
        </div>
      </div>
      <br class="clear-fix" />
    </div>
    
    <%= yield %>
  </body>
</html>